language: node_js
node_js:
- '8'
install:
- npm install
script:
- npm test
before_install:
- openssl aes-256-cbc -K $encrypted_d2204d4b3387_key -iv $encrypted_d2204d4b3387_iv
  -in config.json.enc -out Travis-test/core/config.json -d
